
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Entry txtHost;
	private global::Gtk.Entry txtPort;
	private global::Gtk.HBox hbox1;
	private global::Gtk.CheckButton chkCredentials;
	private global::Gtk.CheckButton chkEnableSSL;
	private global::Gtk.Table tblCredentials;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Entry txtPassword;
	private global::Gtk.Entry txtUserName;
	private global::Gtk.Table table2;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Entry txtFrom;
	private global::Gtk.Entry txtSubject;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtDescription;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label1;
	private global::Gtk.Entry txtTo;
	private global::Gtk.HBox hbox6;
	private global::Gtk.CheckButton chkIsHtml;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button btnSubmit;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnQuit;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Test Smtp Client");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(2));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 3;
		this.vbox1.BorderWidth = ((uint)(3));
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Host: ");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Port: ");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtHost = new global::Gtk.Entry ();
		this.txtHost.CanFocus = true;
		this.txtHost.Name = "txtHost";
		this.txtHost.IsEditable = true;
		this.txtHost.InvisibleChar = '●';
		this.table1.Add (this.txtHost);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtHost]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtPort = new global::Gtk.Entry ();
		this.txtPort.CanFocus = true;
		this.txtPort.Name = "txtPort";
		this.txtPort.IsEditable = true;
		this.txtPort.InvisibleChar = '●';
		this.table1.Add (this.txtPort);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPort]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.chkCredentials = new global::Gtk.CheckButton ();
		this.chkCredentials.CanFocus = true;
		this.chkCredentials.Name = "chkCredentials";
		this.chkCredentials.Label = global::Mono.Unix.Catalog.GetString ("Without Authentication");
		this.chkCredentials.DrawIndicator = true;
		this.chkCredentials.UseUnderline = true;
		this.hbox1.Add (this.chkCredentials);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkCredentials]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.chkEnableSSL = new global::Gtk.CheckButton ();
		this.chkEnableSSL.CanFocus = true;
		this.chkEnableSSL.Name = "chkEnableSSL";
		this.chkEnableSSL.Label = global::Mono.Unix.Catalog.GetString ("Enable SSL");
		this.chkEnableSSL.DrawIndicator = true;
		this.chkEnableSSL.UseUnderline = true;
		this.hbox1.Add (this.chkEnableSSL);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.chkEnableSSL]));
		w7.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.tblCredentials = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.tblCredentials.Name = "tblCredentials";
		this.tblCredentials.RowSpacing = ((uint)(6));
		this.tblCredentials.ColumnSpacing = ((uint)(6));
		// Container child tblCredentials.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("User name: ");
		this.tblCredentials.Add (this.label4);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblCredentials [this.label4]));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblCredentials.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Password: ");
		this.tblCredentials.Add (this.label5);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblCredentials [this.label5]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblCredentials.Gtk.Table+TableChild
		this.txtPassword = new global::Gtk.Entry ();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.Visibility = false;
		this.txtPassword.InvisibleChar = '●';
		this.tblCredentials.Add (this.txtPassword);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tblCredentials [this.txtPassword]));
		w11.TopAttach = ((uint)(1));
		w11.BottomAttach = ((uint)(2));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child tblCredentials.Gtk.Table+TableChild
		this.txtUserName = new global::Gtk.Entry ();
		this.txtUserName.CanFocus = true;
		this.txtUserName.Name = "txtUserName";
		this.txtUserName.IsEditable = true;
		this.txtUserName.InvisibleChar = '●';
		this.tblCredentials.Add (this.txtUserName);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblCredentials [this.txtUserName]));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.tblCredentials);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tblCredentials]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("From: ");
		this.table2.Add (this.label10);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Xalign = 0F;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Subject: ");
		this.table2.Add (this.label11);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtFrom = new global::Gtk.Entry ();
		this.txtFrom.CanFocus = true;
		this.txtFrom.Name = "txtFrom";
		this.txtFrom.IsEditable = true;
		this.txtFrom.InvisibleChar = '●';
		this.table2.Add (this.txtFrom);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtFrom]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtSubject = new global::Gtk.Entry ();
		this.txtSubject.CanFocus = true;
		this.txtSubject.Name = "txtSubject";
		this.txtSubject.IsEditable = true;
		this.txtSubject.InvisibleChar = '●';
		this.table2.Add (this.txtSubject);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtSubject]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table2]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtDescription = new global::Gtk.TextView ();
		this.txtDescription.CanFocus = true;
		this.txtDescription.Name = "txtDescription";
		this.txtDescription.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkScrolledWindow.Add (this.txtDescription);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w20.Position = 4;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("To: ");
		this.hbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtTo = new global::Gtk.Entry ();
		this.txtTo.CanFocus = true;
		this.txtTo.Name = "txtTo";
		this.txtTo.IsEditable = true;
		this.txtTo.InvisibleChar = '●';
		this.hbox3.Add (this.txtTo);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtTo]));
		w22.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w23.Position = 5;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.chkIsHtml = new global::Gtk.CheckButton ();
		this.chkIsHtml.CanFocus = true;
		this.chkIsHtml.Name = "chkIsHtml";
		this.chkIsHtml.Label = global::Mono.Unix.Catalog.GetString ("HTML Body");
		this.chkIsHtml.DrawIndicator = true;
		this.chkIsHtml.UseUnderline = true;
		this.hbox6.Add (this.chkIsHtml);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.chkIsHtml]));
		w24.Position = 0;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w25.Position = 6;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnSubmit = new global::Gtk.Button ();
		this.btnSubmit.CanFocus = true;
		this.btnSubmit.Name = "btnSubmit";
		this.btnSubmit.UseStock = true;
		this.btnSubmit.UseUnderline = true;
		this.btnSubmit.Label = "gtk-ok";
		this.hbox5.Add (this.btnSubmit);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnSubmit]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox5.Add (this.fixed1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed1]));
		w27.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnQuit = new global::Gtk.Button ();
		this.btnQuit.CanFocus = true;
		this.btnQuit.Name = "btnQuit";
		this.btnQuit.UseStock = true;
		this.btnQuit.UseUnderline = true;
		this.btnQuit.Label = "gtk-quit";
		this.hbox5.Add (this.btnQuit);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnQuit]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w29.PackType = ((global::Gtk.PackType)(1));
		w29.Position = 7;
		w29.Expand = false;
		w29.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 323;
		this.DefaultHeight = 378;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.chkCredentials.Toggled += new global::System.EventHandler (this.OnChkCredentialsToggled);
		this.btnSubmit.Clicked += new global::System.EventHandler (this.OnBtnSubmitClicked);
		this.btnQuit.Clicked += new global::System.EventHandler (this.OnBtnQuitClicked);
	}
}
